name: Deploy to Client Repository

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "DEPLOY" to confirm deployment to client repo'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'DEPLOY'
    
    steps:
      - name: Checkout company repo
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "Tahir Aziz"
          git config --global user.email "tahiraziznu@gmail.com"

      - name: Push to client repository
        run: |
          git remote add client https://${{ secrets.CLIENT_TOKEN }}@github.com/tahiraziznu/client-r.git
          git push client dev:main --force