name: Deploy Code to Client Repo

on:
  workflow_dispatch:
    inputs:
        commitMessage:
          description: 'Commit message'
          required: true
          default: ''
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'src/**'
  #     - 'public/**'
  #     - 'components/**'
  #     - 'utils/**'
  #     - 'package.json'
  #     - 'tsconfig.json'
  #     - 'next.config.js'
      
  # pull_request:
  #   branches:
  #     - main
  #   types: [closed]

jobs:
  sync-client-repo:
    # if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    if: github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Team Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Clone client-repo and sync files
        env:
          CLIENTPAT: ${{ secrets.CLIENTPAT }}
        run: |
          echo "🔐 Token starts with: ${CLIENTPAT:0:4}****"

          git clone https://x-access-token:${CLIENTPAT}@github.com/tahiraziznu/client-r.git client-repo
          
          rsync -av --progress ./ ./client-repo \
            --exclude .git \
            --exclude '.github/***' \
            --exclude 'node_modules/***' \
            --exclude .github \
            --exclude client-repo \
            --include 'src/***' \
            --include 'public/***' \
            --include 'components/***' \
            --include 'utils/***' \
            --include 'package.json' \
            --include 'tsconfig.json' \
            --include 'next.config.js' \
            --exclude 'public/test-data/***' \
            --exclude '.env' \
            --exclude '.vscode/***' \
            --exclude '*.test.*' \
            --exclude '*' 

          cd client-repo
          git config user.name "Tahir Aziz"
          git config user.email "tahiraziznu@gmail.com"
          git add .

          commit_msg="${{ github.event.inputs.commitMessage }}"
          if [ -z "$commit_msg" ]; then
            commit_msg=$(git -C .. log -1 --pretty=%B)
          fi


          git commit -m "$commit_msg" || echo "⚠️ No changes to commit"
          git push origin main