name: Deploy Team Code to Client Repo (Safe Merge)

on:
  workflow_dispatch:
    inputs:
      commitMessage:
        description: 'Commit message'
        required: true
        default: 'Sync from team-r to client-r'

jobs:
  safe-sync-to-client:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout team-r (this repo)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git Identity
        run: |
          git config --global user.name "Tahir Aziz"
          git config --global user.email "tahiraziznu@gmail.com"

      - name: Clone client-r repo and merge team-r code
        env:
          CLIENTPAT: ${{ secrets.CLIENTPAT }}
        run: |
          echo "🔐 Cloning client-r repository..."
          git clone https://x-access-token:${CLIENTPAT}@github.com/tahiraziznu/client-r.git client-repo
          cd client-repo

          echo "🔁 Adding mosamaatcode/team-r as remote..."
          git remote add team-r https://github.com/mosamaatcodezac/team-r.git
          git fetch team-r

          echo "🔀 Merging team-r/main into client-r/main..."
          git checkout main
          git merge team-r/main --no-edit || echo "⚠️ Merge completed with conflicts — please resolve manually."

          echo "🧪 Checking for merge conflicts..."
          if git ls-files -u | grep -q .; then
            echo "❌ Merge conflict detected. Please resolve manually in the client repo."
            exit 1
          fi

          echo "✅ Committing and pushing merged code to client-r..."
          git commit -am "${{ github.event.inputs.commitMessage }}" || echo "⚠️ Nothing to commit"
          git push origin main
