name: Auto Sync to Client Repo

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'components/**'
      - 'utils/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'next.config.js'
      
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  sync-client-repo:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout team-repo code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Clone client-repo and sync files
        env:
          CLIENTPAT: ${{ secrets.CLIENTPAT }}
        run: |
          echo "🔐 Token starts with: ${CLIENTPAT:0:4}****"

          # Clone client-repo to a subfolder
          git clone https://x-access-token:${CLIENTPAT}@github.com/tahiraziznu/client-r.git client-repo
          
          # Remove all existing files in client-repo
          rm -rf client-repo/*

          # Copy everything from team-repo (excluding .git and client-repo folder)
          rsync -av --progress ./ ./client-repo --exclude .git --exclude client-repo

          cd client-repo

          git config user.name "Tahir Aziz"
          git config user.email "tahiraziznu@gmail.com"

          git add .

          # Use latest commit message from team-repo
          commit_msg=$(git -C .. log -1 --pretty=%B)
          git commit -m "$commit_msg" || echo "⚠️ No changes to commit"

          git push origin main