name: Deploy Team Code to Client Repo (Safe Merge)

on:
  workflow_dispatch:
    inputs:
      commitMessage:
        description: 'Commit message'
        required: true
        default: 'Sync from team repo to client repo'

jobs:
  safe-sync-to-client:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout Team Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # important for full history and merge base

      - name: Setup Git Identity
        run: |
          git config --global user.name "Tahir Aziz"
          git config --global user.email "tahiraziznu@gmail.com"

      - name: Clone Client Repo and Merge Team Code
        env:
          CLIENTPAT: ${{ secrets.CLIENTPAT }}
        run: |
          echo "🔐 Cloning client repo..."
          git clone https://x-access-token:${CLIENTPAT}@github.com/tahiraziznu/client-r.git client-repo
          cd client-repo

          echo "🔁 Adding team repo as remote..."
          git remote add team-repo $GITHUB_SERVER_URL/${{ github.repository }}
          git fetch team-repo

          echo "🔀 Merging team repo code into client repo..."
          git checkout main
          git merge team-repo/main --no-edit || echo "⚠️ Merge completed with conflicts — please resolve manually."

          echo "🧪 Checking for conflicts..."
          if git ls-files -u | grep -q .; then
            echo "❌ Merge conflict detected. Please resolve manually in the client repo."
            exit 1
          fi

          echo "✅ Pushing merged code to client repo..."
          git commit -am "${{ github.event.inputs.commitMessage }}" || echo "⚠️ Nothing to commit"
          git push origin main
