name: Sync to Client Repo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  sync-code:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout team-repo code
        uses: actions/checkout@v3

      - name: Push to client-repo
        env:
          CLIENTPAT: ${{ secrets.CLIENTPAT }}
        run: |
          git config user.name "Tahir Aziz"
          git config user.email "tahiraziznu@gmail.com"

          echo "Token starts with: ${CLIENTPAT:0:4}****"  # ✅ Bash syntax (correct)

          git remote add client https://x-access-token:${CLIENTPAT}@github.com/tahiraziznu/client-r.git
          git push client HEAD:main --force